name: "ggH_HToSS_MS2_ctauS100"
locations:
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017/ggH/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS2_ctauS100/"
    - "/pnfs/iihe/cms/store/user/almorton/MC/skims2017/ggH/NLO_ggH_HToSS_SmuonHadronFiltered_M125_MS2_ctauS100_ext1/"
total_events: 1223480
cross_section: 21.46
mc: true
histogram: "ggH_HToSS_MS2_ctauS100"
colour: "#a65628"
label: "ggH_HToSS_MS2_ctauS100"
plot_type: "f"


